(use-modules (gi)
             (test automake-test-lib)
             (srfi srfi-1)
             (system foreign))

(typelib-require ("Marshall" "1.0"))

(automake-test
 (let ((returned (list (int8-return-min)
                       (int16-return-min)
                       (int32-return-min)
                       (int64-return-min)
                       (short-return-min)
                       (int-return-min)
                       (long-return-min)))
       (output (list (int8-out-min)
                     (int16-out-min)
                     (int32-out-min)
                     (int64-out-min)
                     (short-out-min)
                     (int-out-min)
                     (long-out-min)))       
       (expected (list (- (expt 2 7))
                       (- (expt 2 15))
                       (- (expt 2 31))
                       (- (expt 2 63))
                       (- (expt 2 (1- (* 8 (sizeof short)))))
                       (- (expt 2 (1- (* 8 (sizeof int)))))
                       (- (expt 2 (1- (* 8 (sizeof long))))))))
   (format #t "Returned: ~S~%" returned)
   (format #t "Output:   ~S~%" output)
   (format #t "Expected: ~S~%" expected)
   (list= = returned output expected)))

