(define-module (gi)
  #:use-module (ice-9 eval-string)
  #:export (send))

(define-syntax send
  (syntax-rules ()
    ((_ s ( m ))
     (call-method s (symbol->string m)))
    ((_ s ( m a ))
     (call-method s (symbol->string m) a))
    ((_ s ( m a b ))
     (call-method s (symbol->string m) a b))
    ((_ s ( m a b c ))
     (call-method s (symbol->string m) a b c))
    ((_ s ( m a b c d ))
     (call-method s (symbol->string m) a b c d ))
    ((_ s ( m a b c d e))
     (call-method s (symbol->string m) a b c d e))
    ((_ s ( m a b c d e f))
     (call-method s (symbol->string m) a b c d e f))
    ((_ s ( m a b c d e f g))
     (call-method s (symbol->string m) a b c d e f g))))

(load-extension "libguile-gi" "gir_init")

(when (defined? 'gcov-reset)
  (export gcov-reset))
(when (defined? 'gcov-dump)
  (export gcov-dump))
