#!/bin/sh

################################################################
# Str-Val Header

echo "
// Autogenerated file
#ifndef GIG_STRVAL_H
#define GIG_STRVAL_H

#include <stdbool.h>
#include <stdint.h>
#include <libguile.h>
" > gig_strval.h

cat gig_strval.i.h \
    | sed 's/TABLE/NameHash/g' \
    | sed 's/ITEM/NameItem/g' \
    | sed 's/TYPE2/scm_t_bits/g' \
    | sed 's/FUNC/name_hash/g' >> gig_strval.h

echo "
#endif
" >> gig_strval.h

################################################################
# Str-Val C file

echo "
// Autogenerated file
#define _XOPEN_SOURCE 700       /* for strdup */
#include <stdlib.h>
#include <string.h>
#include \"gig_strval.h\"
" > gig_strval.c

cat gig_strval.i.c \
    | sed 's/TABLE/NameHash/g' \
    | sed 's/ITEM/NameItem/g' \
    | sed 's/TYPE2/scm_t_bits/g' \
    | sed 's/FUNC/name_hash/g' >> gig_strval.c

echo "
" >> gig_strval.c
