#!/bin/sh

################################################################
# Key-Val Header

echo "
// Autogenerated file
#ifndef GIG_KEYVAL_H
#define GIG_KEYVAL_H

#include <stdbool.h>
#include <stdint.h>
#include \"gig_function.h\"
" > gig_keyval.h

cat gig_keyval.i.h \
    | sed 's/TABLE/FunctionInfoTable/g' \
    | sed 's/ITEM/FunctionInfoItem/g' \
    | sed 's/TYPE1/GIFunctionInfo */g' \
    | sed 's/TYPE2/GigFunction */g' \
    | sed 's/FUNC/function_cache/g' >> gig_keyval.h

cat gig_keyval.i.h \
    | sed 's/TABLE/GtypeHash/g' \
    | sed 's/ITEM/GtypeItem/g' \
    | sed 's/TYPE1/GType/g' \
    | sed 's/TYPE2/scm_t_bits/g' \
    | sed 's/FUNC/gtype_hash/g' >> gig_keyval.h

cat gig_keyval.i.h \
    | sed 's/TABLE/ScmHash/g' \
    | sed 's/ITEM/ScmItem/g' \
    | sed 's/TYPE1/scm_t_bits/g' \
    | sed 's/TYPE2/GType/g' \
    | sed 's/FUNC/scm_hash/g' >> gig_keyval.h


echo "
#endif
" >> gig_keyval.h

################################################################
# Key-Val C file

echo "
// Autogenerated file
#define _XOPEN_SOURCE 700       /* for strdup */
#include <stdlib.h>
#include <string.h>
#include \"gig_keyval.h\"
" > gig_keyval.c

cat gig_keyval.i.c \
    | sed 's/TABLE/FunctionInfoTable/g' \
    | sed 's/ITEM/FunctionInfoItem/g' \
    | sed 's/TYPE1/GIFunctionInfo */g' \
    | sed 's/TYPE2/GigFunction */g' \
    | sed 's/FUNC/function_cache/g' >> gig_keyval.c

cat gig_keyval.i.c \
    | sed 's/TABLE/GtypeHash/g' \
    | sed 's/ITEM/GtypeItem/g' \
    | sed 's/TYPE1/GType/g' \
    | sed 's/TYPE2/scm_t_bits/g' \
    | sed 's/FUNC/gtype_hash/g' >> gig_keyval.c

cat gig_keyval.i.c \
    | sed 's/TABLE/ScmHash/g' \
    | sed 's/ITEM/ScmItem/g' \
    | sed 's/TYPE1/scm_t_bits/g' \
    | sed 's/TYPE2/GType/g' \
    | sed 's/FUNC/scm_hash/g' >> gig_keyval.c

echo "
" >> gig_keyval.c

################################################################
# Str-Val Header

echo "
// Autogenerated file
#ifndef GIG_STRVAL_H
#define GIG_STRVAL_H

#include <stdbool.h>
#include <stdint.h>
#include <libguile.h>
" > gig_strval.h

cat gig_strval.i.h \
    | sed 's/TABLE/NameHash/g' \
    | sed 's/ITEM/NameItem/g' \
    | sed 's/TYPE2/scm_t_bits/g' \
    | sed 's/FUNC/name_hash/g' >> gig_strval.h

echo "
#endif
" >> gig_strval.h

################################################################
# Str-Val C file

echo "
// Autogenerated file
#define _XOPEN_SOURCE 700       /* for strdup */
#include <stdlib.h>
#include <string.h>
#include \"gig_strval.h\"
" > gig_strval.c

cat gig_strval.i.c \
    | sed 's/TABLE/NameHash/g' \
    | sed 's/ITEM/NameItem/g' \
    | sed 's/TYPE2/scm_t_bits/g' \
    | sed 's/FUNC/name_hash/g' >> gig_strval.c

echo "
" >> gig_strval.c
