name: MacOS latest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: env
      run: export LANG=C.UTF-8 TERM=dumb VERBOSE=true TZ=America/Los_Angeles
    - name: install packages
      run: |
        brew install guile autoconf automake gobject-introspection
    - name: look for guile
      run: ls -l /usr/bin/gu*
    - name: make dist directory
      run: mkdir `pwd`/dist
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure --enable-hardening --with-gnu-filesystem-hierarchy --prefix=`pwd`/dist
    - name: make
      run: make
    - name: make check
      run: |
        make check
        cat test-suite.log
      shell: bash {0}
    - name: make install
      run: make install
    - name: make distcheck
      run: make distcheck
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
    - name: Uncompress tarballs
      run: gunzip *.tar.gz
    - name: Archive tarball
      uses: actions/upload-artifact@v3
      with:
        name: tarball
        path: guile_gi*tar
    - name: Archive test logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: test-suite.log
