name: Ubuntu 20.04 w/ Guile 3.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: env
      run: export LANG=C.UTF-8 TERM=dumb VERBOSE=true DEBIAN_FRONTEND=noninteractive TZ=America/Los_Angeles
    - name: install packages
      run: sudo apt-get install -y libgirepository1.0-dev guile-3.0-dev gnulib texlive
    - name: look for guile
      run: ls -l /usr/bin/gu*
    - name: make dist directory
      run: mkdir `pwd`/dist
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure --enable-hardening --with-gnu-filesystem-hierarchy --prefix=`pwd`/dist
    - name: make
      run: make
    - name: make check
      run: |
        make check
        cat test-suite.log
      shell: bash {0}
    - name: make install
      run: make install
    - name: make distcheck
      run: make distcheck
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
    - name: Uncompress tarballs
      run: gunzip *.tar.gz
    - name: Archive tarball
      uses: actions/upload-artifact@v2
      with:
        name: tarball
        path: guile_gi*tar
    - name: Archive test logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: test-suite.log
